version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
