apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: tuusuario/nest-backend:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: nest-backend
  namespace: prod
spec:
  selector:
    app: nest-backend
  ports:
    - port: 80
      targetPort: 3000
