apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: prod
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=    # "postgres" en base64
  POSTGRES_USER: YWRtaW4=            # "admin" en base64
